### ISSUE TITLE
Grabber

### ISSUE THREAD

**Issue by 6nz** [xtekky/Nitro-Generator#1]
token grabber...

**Comment by xtekky** [comment]
please don't say such tings without proof.

**Comment by 6nz** [comment]
> please don't say such tings without proof.

I reversed the exe lmao

**Comment by 6nz** [comment]
![image](https://user-images.githubusercontent.com/74118308/173367542-cdd9bcaf-c68c-400b-a904-4fe00217e82e.png)

**Comment by jiroawesome** [comment]
what tool are you using for that scanner?
