### ISSUE TITLE
100% malware 

### ISSUE THREAD

**Issue by DinoFengz** [xtekky/Nitro-Generator#2]

**Comment by xtekky** [comment]
Hi, if you show proof I will give you 1k € ; ), good luck finding the malware ! Why ? Because there is none !

**Comment by 6nz** [comment]
@xtekky Expalin
![image](https://user-images.githubusercontent.com/74118308/173364975-eb321477-d929-44b5-9e1d-3f32a0e704ce.png)

**Comment by 6nz** [comment]
?????

**Comment by xtekky** [comment]
Because the obfuscation I use has a trolling layer, so skids or dumbasses like u just showed u are think that it's a grabber

**Comment by 6nz** [comment]
lmfao
